from random import shuffle, choice, randint
from string import ascii_letters as characters

#adding space into the range of characters
characters += "    "
email_domain_list = ["@gmail.com","@hotmail.com","@yahoo.com","@outlook.com"]

def generateRowCsv():
    #generating a string
    name = "".join([choice(characters) for size in range(randint(5,12))])

    #cutting off spaces at the beginning and at the end of the string
    name = name.strip().title()

    #a random integer
    age = str(randint(15,80))

    #a string in lowercase
    email = "".join(name.split()).lower() + choice(email_domain_list)

    #returning a string formatted as csv row
    return f"{name},{age},{email}"


def generateFile(fileName,number_of_rows):
    """
    This function takes a file name and a number of rows to generate.
    It genarates a CSV file containing rows generated by the
        generateRowCsv()
    function.
    """
    print(f"Generating the file {fileName}.")
    f = open(fileName,"w")
    for row in range(number_of_rows):
        f.write(generateRowCsv() + "\n")
    f.close()
    print("Done.")






